# Introduction to Scipy

In [1]:
import scipy as sp 

In [2]:
s=sp.rand(10)
print(s)
print(len(s))

[0.29236585 0.68769716 0.85839553 0.28893785 0.05809276 0.53001054
 0.6040244  0.73224212 0.1157693  0.3648068 ]
10


C:\Users\Dell\AppData\Local\Temp\ipykernel_4244\1879244938.py:1: DeprecationWarning: scipy.rand is deprecated and will be removed in SciPy 2.0.0, use numpy.random.rand instead
  s=sp.rand(10)


In [3]:
print("Mean :",s.mean())

Mean : 0.4532342312836654


In [4]:
print("Mean : {0:5.2f}".format(s.mean()))

Mean :  0.45


In [5]:
print("Min :",s.min())
print("Minimum  : {0:6.2f}".format(s.min()))

Min : 0.05809275527057556
Minimum  :   0.06


In [6]:
print("Max :",s.max())
print("Maximum : {0:8.1f}".format(s.max()))

Max : 0.8583955275400647
Maximum :      0.9


# Special Functions - Exponential

In [1]:
import scipy as sp
from scipy import special as spl #import scipy.special as spl (Here special is the submodule of scipy)

In [2]:
x=spl.exp10(4) 
print(x)

10000.0


In [3]:
y=spl.exp10([2,3,4])
print(y)

[  100.  1000. 10000.]


In [4]:
z=spl.exp2(3)
print(z)

8.0


In [5]:
Z=spl.exp2([2,4,6,8])
print(Z)

[  4.  16.  64. 256.]


# Special Functions - Trigonometric Functions

In [1]:
import scipy as sp
from scipy import special as spl #import scipy.special as spl

In [2]:
a=spl.sindg(90) #In degrees 
print(a) 

1.0


In [3]:
a=spl.cosdg(60)
print(a)

0.49999999999999994


In [4]:
a=round(spl.cosdg(60),1) #We are rounding the output since, cos60=1/2=0.5
print(a)

0.5


In [5]:
a=spl.tandg(45)
print(a)

1.0


# Integration - General Integration and Double Integration

In [1]:
import scipy as sp
from scipy import integrate #import scipy.integrate (Here integrate is the submodule of scipy)

In [2]:
a=lambda x: ((x**2)-(4*x)+5)
i=integrate.quad(a,0,1)
print(i)

(3.3333333333333335, 3.700743415417189e-14)


In [3]:
b=lambda x,y:x*y**3 #Double Integration
c=-1
d=1
i=integrate.dblquad(b,0,2,c,d)
print(i)

(0.0, 8.791154598512528e-14)


In [4]:
e=lambda x,y,z:x**2+y**2+z**2+1 #Triple Integration
i=integrate.tplquad(e,1,3,2,3,0,1)
print(i)

(24.0, 2.6645352591003757e-13)


# Linear Algebraic Equations

In [1]:
import numpy as np
import scipy as sp
from scipy import linalg

In [2]:
a=np.array([[3,2],[1,-1]]) #Linear algebraic Functions 3x+2y=2 and x-y=4 represented in matrix form (2x2)
b=np.array([[2],[4]])
x=linalg.solve(a,b)
print(x)

[[ 2.]
 [-2.]]


In [3]:
c=np.array([[3,2,-5],[1,-2,3],[4,-1,-2]]) #Linear algebraic Functions 3x+2y-5z=2, x-2y+3z=4 and 4x-y-2z=-1 represented in matrix form (3x3) 
d=np.array([[2],[4],[-1]])
x=linalg.solve(c,d)
print(x)

[[3.85714286]
 [7.        ]
 [4.71428571]]


# If it is not a square matrix (Least Squares)

In [4]:
a=np.array([[3,2,-5],[1,-2,3]]) #Linear Least Squares 3x+2y-5z=2, x-2y+3z=4 represented in matrix form (2x3)
b=np.array([[2],[4]])
x=linalg.lstsq(a,b) 
print(x)

(array([[ 1.66666667],
       [-0.66666667],
       [ 0.33333333]]), array([], dtype=float64), 2, array([6.78232998, 2.44948974]))


Whenever we use lstsq it gives four values in the output which are x(consists of x,y,z values), resident ID, rank and sigma, but we need only the values of x,y&z. So, we can store the four values in four variables and print only 
x.

In [5]:
a=np.array([[3,2,-5],[1,-2,3]])
b=np.array([[2],[4]])
x,resid,rank,sigma=linalg.lstsq(a,b) 
print(x)

[[ 1.66666667]
 [-0.66666667]
 [ 0.33333333]]
