
# Introduction to Numpy 

In [1]:
import numpy as np #Importing numpy as np alias

In [2]:
print(np.__version__) #For checking Numpy version

1.23.5


In [3]:
arr=np.array([15,16,17])
print(arr)
print(type(arr))

[15 16 17]
<class 'numpy.ndarray'>


In [4]:
ar1=np.array([116,"Yash",3.142])
print(ar1)
print(type(ar1))

['116' 'Yash' '3.142']
<class 'numpy.ndarray'>


# Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).
Nested arrays means arrays that have arrays as their elements.

In [5]:
import numpy as np

In [6]:
a=np.array(20) #Will create 0-Dimensional Array
print(a) 

20


In [7]:
print(np.array((1,2,3))) #Will create one dimensional array where this array contains 0-dimensional arrays as its elements

[1 2 3]


In [8]:
print(np.array([(1,2,3),(4,5,6),(7,8,9)])) #Will create two dimensional array where this array contains one dimensional arrays as its elements

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(np.array([[(1,2,3),(4,5,6),(7,8,9)],[(11,12,13),(14,15,16),(17,18,19)]])) #Will create three dimensional array where this array contains two dimensional arrays as its elements

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [10]:
print(np.zeros(5)) #Will create 1D array of zeros

[0. 0. 0. 0. 0.]


In [11]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
print(np.zeros((3,4),dtype=int)) #Will create 3x3 array with values of 8 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
print(np.ones((3,4))) #Will print 3x4 ones in the matrix

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
print(np.full((3,4),(5))) #Will create 3x3 array with values of 8

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
print(np.eye(4)) #Will create 3x3 with 0 and 1 diagnol identity matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
print(np.linspace(5,50,10)) #Will create 5 evenly divides values from 0 to 50(Float)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [17]:
print(np.arange(10,30,5)) #(int) create an array of values from o to less than 10 with step of 5

[10 15 20 25]


# Check Number of Dimensions and Shape of arrays

In [1]:
import numpy as np

In [2]:
a=np.array(20) #0-D array
print(a)
print(a.ndim) #ndim is an attribute that tells us how many dimensions the array have
print(a.shape) 

20
0
()


In [3]:
print(np.array((1,2,3))) #1-D array
print(np.array((1,2,3)).ndim)
print(np.array((1,2,3)).shape)

[1 2 3]
1
(3,)


In [4]:
print(np.array([(1,2,3),(4,5,6),(7,8,9)])) #2-D array
print(np.array([(1,2,3),(4,5,6),(7,8,9)]).ndim)
print(np.array([(1,2,3),(4,5,6),(7,8,9)]).shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [5]:
print(np.array([[(1,2,3),(4,5,6),(7,8,9)],[(11,12,13),(14,15,16),(17,18,19)]])) #3-D array
print(np.array([[(1,2,3),(4,5,6),(7,8,9)],[(11,12,13),(14,15,16),(17,18,19)]]).ndim)
print(np.array([[(1,2,3),(4,5,6),(7,8,9)],[(11,12,13),(14,15,16),(17,18,19)]]).shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
3
(2, 3, 3)


# Generating random numbers

In [22]:
import numpy as np

In [23]:
print(np.random.rand(4,5)) #Will create 2x3 array of random floats between 0-1

[[0.89028596 0.13738248 0.63764134 0.7413778  0.741899  ]
 [0.49040294 0.44380693 0.50273422 0.89780695 0.13148381]
 [0.64218544 0.6316437  0.74114761 0.29777751 0.9500957 ]
 [0.97961146 0.10484175 0.79168917 0.56791897 0.614586  ]]


In [24]:
print(np.random.rand(12))

[0.11180864 0.6759856  0.60733531 0.47679422 0.23881637 0.97804352
 0.80031912 0.94902727 0.9469329  0.10318622 0.38175651 0.38802447]


In [25]:
print(np.random.rand(5,5)*15) #Will create 6x7 array with random floats between 0-4

[[12.40213144  5.43200568  2.20439996  4.06166622  1.75124861]
 [ 0.73828103  5.34486856  0.14645632  2.00329485  4.79480737]
 [ 3.69154648  7.97530208  0.46626999 13.22727736 14.50623678]
 [14.5490869   1.41277915  9.8835511   5.75104756 12.5246191 ]
 [13.66940087  7.40209135 13.87814782  2.28959666  2.87856856]]


In [26]:
print(np.random.choice([8,2,6,4,7,9])) #Pick any number from thr array randomly

4


In [27]:
print(np.random.choice([8,2,6,4,7,9],[3,3]))

[[6 9 9]
 [4 8 6]
 [7 4 6]]


In [28]:
print(np.random.randint(15,size=(25)))

[ 8  8 10  4  2 13 11  5  3  8 13  2  8 12  6  3  7 14  4 12 11  5 11 12
 14]


In [29]:
print(np.random.randint(20,size=(5,5))) #Will create array with random ints between 0-4

[[ 6 19  1 12  0]
 [ 9  4 13  5  5]
 [16  3 17 16 15]
 [12 19 16  8 19]
 [11  4 16 16 13]]


In [30]:
print(np.random.randint(15,25,size=(4,3)))

[[20 18 21]
 [21 23 17]
 [17 16 20]
 [15 21 17]]


# Inspecting Properties

In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

In [3]:
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [4]:
print(arr.size) #Will print the number of elements in the array

15


In [5]:
print(arr.shape) #Will print the size (rxc) of array

(5, 3)


In [6]:
print(arr.dtype) #Will print the data type of array

int32


In [8]:
print(arr.tolist()) #Will convert array to list

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]


In [7]:
ar1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15.5]]) #Here one of the elements in this array is float, So it will consider all elements in this array as float
print(ar1.dtype)

float64


# Copying/Sorting/Reshaping

In [1]:
import numpy as np

In [2]:
arr=np.array([[9,12,8],[11,7,9]])
print(arr)

[[ 9 12  8]
 [11  7  9]]


In [3]:
print("Address of arr :",id(arr))

Address of arr : 1749214631216


In [4]:
arr1=arr #Without changing the location
print("Address of arr1 :",id(arr1))

Address of arr1 : 1749214631216


In [5]:
arr2=np.copy(arr) #gives two different address locations
print("Address of arr2 :",id(arr2))

Address of arr2 : 1749210916464


In [6]:
a=np.array([3,2,9,5,1])
print(a)

[3 2 9 5 1]


In [7]:
print(np.sort(a)) #Will sort array

[1 2 3 5 9]


In [8]:
b=np.array(["yash",35,8,35.24,"abc",591])
print(b)

['yash' '35' '8' '35.24' 'abc' '591']


In [9]:
print(np.sort(b)) #Will consider the number which starts with smallest number
#Here among all the numbers in dataset even though we have 8 in the list, 35 comes first since it starts with 3 which is the smallest number

['35' '35.24' '591' '8' 'abc' 'yash']


In [10]:
c=np.array([[9,12,8],[11,7,5]])
print(c)

[[ 9 12  8]
 [11  7  5]]


In [11]:
print(np.sort(c)) #Will sort with respect to row

[[ 8  9 12]
 [ 5  7 11]]


In [12]:
d=np.array([[9,12,8],[11,7,5],[9,5,1]])
print(d)

[[ 9 12  8]
 [11  7  5]
 [ 9  5  1]]


In [13]:
print(d.flatten()) #Will flatten 2D array to 1D array

[ 9 12  8 11  7  5  9  5  1]


In [14]:
e=np.array([[(1,2,3),(4,5,6),(7,8,9)],[(11,12,13),(14,15,16),(17,18,19)]]) #3D array
print(e.flatten()) #Will flatten 3D array to 1D array

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


In [15]:
print(d.T) #Will Transpose the array, which means rows becomes columns and columns becomes rows

[[ 9 11  9]
 [12  7  5]
 [ 8  5  1]]


In [16]:
f=np.array([[9,12,8],[11,7,5],[5,6,1],[1,9,3]])
print(f)

[[ 9 12  8]
 [11  7  5]
 [ 5  6  1]
 [ 1  9  3]]


In [17]:
print(f.reshape(3,4)) #Will reshape the array into 3x4 array without any change in data 
#Since shape of f dataset is 4x3 which contains 12 elements then, reshape is applied which should be equivalent to 12 elements i.e, (3x4),(6x2),(2x6),(12x1),(1x12)

[[ 9 12  8 11]
 [ 7  5  5  6]
 [ 1  1  9  3]]


In [18]:
print(np.resize(f,(4,4))) #Will increase or decrease the size of the array

[[ 9 12  8 11]
 [ 7  5  5  6]
 [ 1  1  9  3]
 [ 9 12  8 11]]


In [21]:
g=np.array([1, 2, 3, 4], ndmin=5)
print(g)
print()
print("number of dimensions :", g.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Adding/Removing Data

In [1]:
import numpy as np

In [2]:
ar=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(ar)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
ar1=np.append(ar,[20,30,40,50]) #Will add the new list at last to the dataset
print(ar1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 20 30 40 50]


In [5]:
ar2=ar1.reshape(5,4)
print(ar2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [20 30 40 50]]


In [6]:
ar3=np.insert(ar,6,(60,70,80,90))
print(ar3)

[ 1  2  3  4  5  6 60 70 80 90  7  8  9 10 11 12 13 14 15 16]


In [7]:
ar4=ar3.reshape(5,4)
print(ar4)

[[ 1  2  3  4]
 [ 5  6 60 70]
 [80 90  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
ar5=np.delete(ar,2,axis=0)
print(ar5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [13 14 15 16]]


In [9]:
ar6=np.delete(ar,2,axis=1)
print(ar6)

[[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]
 [13 14 16]]


# Combining/Splitting

In [1]:
import numpy as np

In [2]:
arr=np.array([[10,11,12,13,14],[3,1,2,3,4],[21,20,30,40,50],[56,39,67,45,57]])
arr1=np.array([[4,5,6,7,8],[21,22,23,24,25],[31,32,33,34,35]])
arr2=np.array([[4,5,6,7],[21,22,23,24],[31,32,33,34],[40,41,42,43]])
print(arr)
print(arr1)
print(arr2)

[[10 11 12 13 14]
 [ 3  1  2  3  4]
 [21 20 30 40 50]
 [56 39 67 45 57]]
[[ 4  5  6  7  8]
 [21 22 23 24 25]
 [31 32 33 34 35]]
[[ 4  5  6  7]
 [21 22 23 24]
 [31 32 33 34]
 [40 41 42 43]]


In [3]:
print(np.concatenate((arr,arr1),axis=0)) #Will add rows to the arr

[[10 11 12 13 14]
 [ 3  1  2  3  4]
 [21 20 30 40 50]
 [56 39 67 45 57]
 [ 4  5  6  7  8]
 [21 22 23 24 25]
 [31 32 33 34 35]]


In [4]:
print(np.concatenate((arr,arr1),axis=1)) #Will add columns to arr

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3

Here we are getting error because With respect to columns, rows should be same for both arrays and with respect to rows, columns should be same for both arrays.

In [5]:
print(np.split(arr2,4)) #Will split array to sub array based on rows

[array([[4, 5, 6, 7]]), array([[21, 22, 23, 24]]), array([[31, 32, 33, 34]]), array([[40, 41, 42, 43]])]


In [6]:
arr3=np.array([[4,5,6,7,8,2],[21,22,23,24,21,25],[31,32,33,21,34,35],[40,41,33,42,43,44]])
print(arr3)

[[ 4  5  6  7  8  2]
 [21 22 23 24 21 25]
 [31 32 33 21 34 35]
 [40 41 33 42 43 44]]


In [7]:
print(np.hsplit(arr3,3)) #Will array to sub array horizontally

[array([[ 4,  5],
       [21, 22],
       [31, 32],
       [40, 41]]), array([[ 6,  7],
       [23, 24],
       [33, 21],
       [33, 42]]), array([[ 8,  2],
       [21, 25],
       [34, 35],
       [43, 44]])]


# Indexing/slicing/subsetting

In [1]:
import numpy as np

In [2]:
arr=np.array([10,11,4,13,14,2])
arr1=np.array([[12,19,2,3,14,18],[29,1,23,4,25,26]])
print(arr)
print(arr1)

[10 11  4 13 14  2]
[[12 19  2  3 14 18]
 [29  1 23  4 25 26]]


In [3]:
print(arr[4]) #Will give the element at index 4

14


In [4]:
print(arr1[1,3]) #Will give the elements of 2D array

4


In [5]:
arr[1]=9 #Will assign array element on index 1 the value 4
print(arr)

[10  9  4 13 14  2]


In [6]:
arr1[1,4]=10 #Assigns array element on index [1][3] the value 10
print(arr1)

[[12 19  2  3 14 18]
 [29  1 23  4 10 26]]


In [7]:
print(arr[:3]) #Will give the elements in array with positions of 0,1,2

[10  9  4]


In [8]:
print(arr1[0:2,0:1]) #Will give the elements on rows 0,1,2 at column 4

[[12]
 [29]]


In [9]:
print(arr1[:1]) #Will return rows in 2D array

[[12 19  2  3 14 18]]


In [10]:
print(arr1[:,:2]) #Will return the elements at index 1 on all rows

[[12 19]
 [29  1]]


In [11]:
print(arr<5) #Will return an array with boolean values, returns True whereever the number in arr is lessthan 5 else returns False

[False False  True False False  True]


In [12]:
print((arr>3)&(arr<5)) #Will return an array with boolean values

[False False  True False False False]


In [13]:
print(arr1<5)

[[False False  True  True False False]
 [False  True False  True False False]]


# Scalar Math

In [1]:
import numpy as np

In [2]:
arr=np.array([10,11,12,13,14,15])
arr1=np.array([[10,11,12,13,14,15],[21,22,23,24,25,26]])
print(arr)
print(arr1)

[10 11 12 13 14 15]
[[10 11 12 13 14 15]
 [21 22 23 24 25 26]]


In [3]:
print("Scalar vector addition :\n",np.add(arr,2)) #Will add 2 to each array element

Scalar vector addition :
 [12 13 14 15 16 17]


In [4]:
print(np.add(arr1,2)) #Will add 2 to each array element

[[12 13 14 15 16 17]
 [23 24 25 26 27 28]]


In [5]:
print(np.subtract(arr1,1)) #Will subtract 1 from each and every array element

[[ 9 10 11 12 13 14]
 [20 21 22 23 24 25]]


In [6]:
print(np.multiply(arr1,2)) #Will multiply each and every array element with 2

[[20 22 24 26 28 30]
 [42 44 46 48 50 52]]


In [7]:
print(np.divide(arr1,2)) #Will divide each and every array element with 2

[[ 5.   5.5  6.   6.5  7.   7.5]
 [10.5 11.  11.5 12.  12.5 13. ]]


In [8]:
print(np.power(arr,2)) #Will

[100 121 144 169 196 225]


# Vector Math

In [1]:
import numpy as np

In [2]:
arr=np.array([[1.1,2.8,3.6,4],[5.2,6.5,7.8,8.2]])
arr1=np.array([[9,2,11,12],[13,14,15,-16]])
arr2=np.array([[9,2,11,12],[13,14,15,16]])
print(arr)
print(arr1)
print(arr2)

[[1.1 2.8 3.6 4. ]
 [5.2 6.5 7.8 8.2]]
[[  9   2  11  12]
 [ 13  14  15 -16]]
[[ 9  2 11 12]
 [13 14 15 16]]


In [3]:
print(np.array_equal(arr2,arr1)) #Will return True if each and every element in arr2 matches with arr1

False


In [4]:
print(np.sqrt(25)) #Square root of 25

5.0


In [5]:
print(np.sqrt(arr2)) #Will give the square root for each and every element in the array

[[3.         1.41421356 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]]


In [6]:
print(np.cos(arr2)) #Will give cos of each element in the array in radians

[[-0.91113026 -0.41614684  0.0044257   0.84385396]
 [ 0.90744678  0.13673722 -0.75968791 -0.95765948]]


In [22]:
print(np.sin(90)) #In radians
print(np.sin(1.5)) #In degrees (1 degree=0.0175 radian)

0.8939966636005579
0.9974949866040544


In [8]:
print(np.log(arr2)) #Will give natural log of each element

[[2.19722458 0.69314718 2.39789527 2.48490665]
 [2.56494936 2.63905733 2.7080502  2.77258872]]


In [9]:
print(np.abs(arr1)) #Will give absolute value of each element in the array

[[ 9  2 11 12]
 [13 14 15 16]]


In [10]:
print(np.ceil(arr)) #Will rounds up to the nearest value (Highest)

[[2. 3. 4. 4.]
 [6. 7. 8. 9.]]


In [11]:
print(np.floor(arr)) #Will rounds up to the nearest value (Lowest)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [12]:
print(np.round(arr)) #Will rounds up to the nearest value 

[[1. 3. 4. 4.]
 [5. 6. 8. 8.]]


In [13]:
arr3=np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
print(np.mean(arr3,axis=1)) #Will give mean for the specified axis

[2.5 6.5]


In [15]:
print(arr3.sum()) #Will sum up th elements the in array

36


In [16]:
print(arr3.min()) #Will give the minimun value in array

1


In [17]:
print(arr3.max(axis=0)) #Will give the maximum value for the specified axis

[5 6 7 8]


In [18]:
arr4=np.array([[3,4],[5,6]])
print(arr4)

[[3 4]
 [5 6]]


In [19]:
print(np.var(arr)) #Will return the variance of the array

5.412499999999999


In [20]:
print(np.var(arr,axis=0)) #Will return variance for the specified axis

[4.2025 3.4225 4.41   4.41  ]


In [21]:
print(np.std(arr,axis=0)) #Will return the standard deviation for the specified axis

[2.05 1.85 2.1  2.1 ]
